### ISSUE TITLE
Enable local execution of Lambda

### ISSUE THREAD

**Issue by lakruzz** [prolike/GitLabelWizard#34]
### Problem
We can not debug! We're working in the blind!

### Feature

Enable debugging, either by connecting to it remote - or by running lambda locally - somehow

### Value

We, have access to debug and trace information from our program executions.

---

We need to be able to do step-through- debugging when executing our Python code.

Set AWS SAM up locally and enable debug.

Have a look at
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging.html

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-python.html

**Comment by astyltsvig** [comment]
Not relevant anymore
