### ISSUE TITLE
Use the Git Phlow

### ISSUE THREAD

**Issue by lakruzz** [prolike/GitLabelWizard#35]
The lambda functions are stored on AWS, they should be stored in git, and the they to AWS should be triggered by a push - use Git Phlow!

**Comment by astyltsvig** [comment]
I have just take a moment and think over your suggestion, and i have to say that I am not fully agreeing with this setup. I would rather give CircleCi responsibility for deploying into our amazon lambda. 
So my suggestion is following:
Git phlow resolve a issue -> git deliver -> circleci build success -> circle ci deploy to amazon lambda

**Comment by astyltsvig** [comment]
Related to #49

**Comment by astyltsvig** [comment]
Not relevant anymore
