### ISSUE TITLE
Set up Circle CI

### ISSUE THREAD

**Issue by lakruzz** [prolike/GitLabelWizard#36]
A Docker based solution would be preferable

**Comment by Ansty93** [comment]
reference #44 + #43 + #41

**Comment by astyltsvig** [comment]
I realized the task might be too big.

We need to do following to perform a perfect circleci build

1. Set up a docker environment with python
2. Set up the AWS cli lambda local debug
3. Install python libraries from requirements.txt to tagret local directory (-t ./) 
4. Run local lambda and test python app
5. Build a zip with dependencies and app
6. Deploy the zip to amazon aws lambda
7. Success

It requires alot of study how to perform jobs in circleci with these steps. Thats why i assigned the "too big" label to this task. We should rather split the task up in small jobs

**Comment by astyltsvig** [comment]
Not relevant anymore - Using google functions instead
